-- Primeiro, vamos dropar a tabela se ela existir
DROP TABLE IF EXISTS servicos;

-- Agora vamos criar a tabela com os nomes de colunas em snake_case
CREATE TABLE servicos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitante varchar(255) NOT NULL,
    loja varchar(255) NOT NULL,
    servico text NOT NULL,
    orcamento decimal(10,2) NOT NULL,
    infra_speak varchar(255) NOT NULL,
    mes_servico varchar(20) NOT NULL,
    ano_servico integer NOT NULL,
    faturamento varchar(20) NOT NULL DEFAULT 'PENDENTE',
    situacao varchar(20) NOT NULL DEFAULT 'PENDENTE',
    projeto_manutencao varchar(20) NOT NULL DEFAULT 'MANUTENCAO',
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- Criar uma view para manter compatibilidade com o código existente
CREATE OR REPLACE VIEW servicos_view AS
SELECT 
    id,
    solicitante,
    loja,
    servico,
    orcamento,
    infra_speak as "infraSpeak",
    mes_servico as "mesServico",
    ano_servico as "anoServico",
    faturamento,
    situacao,
    projeto_manutencao as "projetoManutencao",
    created_at,
    updated_at
FROM servicos; 